apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "promxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promxy.labels" . | nindent 4 }}
data:
  config.yaml: |
    promxy:
      server_groups:
        - kubernetes_sd_configs:
            - role: {{ .Values.prometheus.kubernetes_sd_configs.role }}
          relabel_configs:
            - source_labels: [__meta_kubernetes_service_name]
              regex: {{ .Values.prometheus.kubernetes_sd_configs.serviceName }}
              action: keep
            - source_labels: [__meta_kubernetes_endpoint_port_name]
              regex: {{ .Values.prometheus.kubernetes_sd_configs.portName }}
              action: keep
