apiVersion: v1
kind: Service
metadata:
  name: {{ include "promxy.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "promxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8082
      protocol: TCP
      name: web
  selector:
    {{- include "promxy.selectorLabels" . | nindent 4 }}
